apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-webserver-pvc
  labels:
    app: html-webserver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: html-webserver-service
  labels:
    app: html-webserver
spec:
  selector:
    app: html-webserver
  type: NodePort
  ports:
  - nodePort: 30000
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-webserver-dep
  labels:
    app: html-webserver
spec:
  selector:
    matchLabels: 
      app: html-webserver
  template:
    metadata:
      name: html-webserver-pod
      labels:
        app: html-webserver
    spec:
      containers:
      - name: html-webserver-con
        image: httpd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mypvc
          mountPath: /var/log/httpd
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: html-webserver-pvc       
        

