apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-webserver-pvc
  labels:
    app: php-webserver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: php-webserver-service
  labels:
    app: php-webserver
spec:
  selector:
    app: php-webserver
  type: NodePort
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-webserver-dep
  labels:
    app: php-webserver
spec:
  selector:
    matchLabels: 
      app: php-webserver
  template:
    metadata:
      name: php-webserver-pod
      labels:
        app: php-webserver
    spec:
      containers:
      - name: php-webserver-con
        image: vimal13/apache-webserver-php
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mypvc
          mountPath: /var/log/httpd
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: php-webserver-pvc       
        